version: "3.8"
services:
  gadm-db:
    image: postgis/postgis:16-3.5
    platform: linux/x86_64
    container_name: gadm-db
    restart: always
    environment:
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gadm
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
