services:
  gadm-db:
    image: postgis/postgis:latest
    platform: linux/amd64
    container_name: ${DB_HOST}
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - gadm_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  gadm-migrations:
    build:
      context: ./gadm-migrations
      dockerfile: Dockerfile
    image: ghcr.io/christopherzinger/gadmmigrationservice:latest
    platform: linux/amd64
    container_name: gadm-migrations
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - ${DB_HOST}
    restart: "no" # Run once and exit
    command: ["up"]

  gadm-api:
    build:
      context: ./gadm-api
      dockerfile: Dockerfile
    image: ghcr.io/christopherzinger/gadmapi:latest
    platform: linux/amd64
    container_name: gadm-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    depends_on:
      - ${DB_HOST}
    restart: unless-stopped

volumes:
  gadm_db_data: