version: "3.8"

services:
  gadm-api:
    image: gadm-api:latest
    platform: linux/amd64
    container_name: gadm-api-test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GADM_DB_NAME: ${GADM_DB_NAME}
      POSTGRES_SUPERUSER_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD}
      ADMIN_GROUP: ${ADMIN_GROUP}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      APP_GROUP: ${APP_GROUP}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
