baseURL = 'https://christopherzinger.github.io/gadm/'
languageCode = 'en-us'
title = 'GADM API'
theme = 'hugo-book'
publishDir = '../docs'

[params]
  apiBaseUrl = 'api.worldlines.org'
  queryParamPageSize = "page-size"
  queryParamStartAt = "start-at"
  queryParamGid = "gid-"
  pathFeatureCollection = "/api/v1/fc/"
  pathGeojsonl = "/api/v1/geojsonl/"
  pathReverseGeocode = "/api/v1/reverse-geocode/"
